# Generated by Django 3.1.2 on 2020-11-12 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='project.user')),
                ('image', models.ImageField(null=True, upload_to='info')),
                ('name', models.CharField(max_length=128, null=True)),
                ('phone', models.CharField(max_length=128, null=True)),
                ('age', models.IntegerField(null=True)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=10, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('address', models.CharField(max_length=128, null=True)),
            ],
        ),
    ]
