# Generated by Django 3.1.2 on 2020-11-12 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='image',
            field=models.ImageField(blank=True, default='image/blood.jpg', upload_to='info'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='blood',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blood.blood'),
        ),
    ]
