# Generated by Django 3.1.2 on 2020-11-12 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0002_auto_20201112_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dis_name', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='userinfo',
            name='disease',
            field=models.ManyToManyField(to='blood.Disease'),
        ),
    ]
